import { Amaranth, Nunito_Sans } from "next/font/google";
import "../globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import BottomNavbar from "@/components/BottomNavbar";
import PopupButtons from "@/components/PopupButtons";


const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["400"]
});

const amaranth = Amaranth({
  variable: "--font-amaranth",
  subsets: ["latin"],
  weight: ["700"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`relative bg-white ${nunitoSans.variable} ${amaranth.variable} antialiased`}
      >
      <PopupButtons />
      <Navbar />
        {children}
      <Footer/>
      <BottomNavbar />
      </body>
    </html>
  );
}
